#!/bin/bash

NAME="project2019_koperasi"
DIR=/home/pi/project2019/
USER=pi
GROUP=pi
WORKERS=3
BIND=unix:/home/pi/project2019/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=koperasi.settings
DJANGO_WSGI_MODULE=koperasi.wsgi
LOG_LEVEL=error

cd $DIR
source venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
